CREATE TABLE IF NOT EXISTS DF_TRANSACTION
(
    ID                BIGINT NOT NULL AUTO_INCREMENT,
    TRANSACTION_ID    VARCHAR(64) NOT NULL,
    TYPE              CHAR(10) NOT NULL,
    AMOUNT            DOUBLE(13,2) NOT NULL,
    NAMESPACE         VARCHAR(128) NOT NULL,
    USER              VARCHAR(128) NOT NULL,
    CREATE_TIME       DATETIME,
    STATUS            VARCHAR(2) NOT NULL,
    STATUS_TIME       DATETIME,
    PRIMARY KEY (ID)
)  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
)  DEFAULT CHARSET=UTF8;
