CREATE TABLE IF NOT EXISTS DF_RECHARGE
(
    RECHARGE_ID       BIGINT NOT NULL AUTO_INCREMENT,
    AMOUNT            DOUBLE(13,2) NOT NULL,
    NAMESPACE         VARCHAR(128) NOT NULL,
    USER              VARCHAR(128) NOT NULL,
    CREATE_TIME       DATETIME,
    STATUS            VARCHAR(2) NOT NULL,
    STATUS_TIME       DATETIME,
    PRIMARY KEY (RECHARGE_ID)
)  DEFAULT CHARSET=UTF8;

